---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: emr-on-eks
  region: ap-south-1
  version: "1.21"

availabilityZones:
  - ap-south-1a
  - ap-south-1b
managedNodeGroups:
  - name: nodegroup
    desiredCapacity: 3
    instanceType: m5.xlarge
    ssh:
      allow: true
      publicKeyName: mumbai-akshaya
# To enable all of the control plane logs, uncomment below:
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

