---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: emr-on-eks-fargate
  region: ap-south-1
  version: "1.21"


vpc:
  id: "vpc-018631597d8970d7f"
  subnets:
    private:
      ap-south-1a:
        id: "subnet-0eaee7f3989c130ce"
      ap-south-1b:
        id: "subnet-0ee972c4b5ae42e5e"
    public:
      ap-south-1a:
        id: "subnet-06afbd6de4c999944"
      ap-south-1b:
        id: "subnet-0a35f37a52581a5de"
managedNodeGroups:
  - name: nodegroup
    desiredCapacity: 3
    instanceType: m5.large
    ssh:
      allow: true
      publicKeyName: mumbai-akshaya
fargateProfiles:
  - name: fp-default
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: default
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system
# To enable all of the control plane logs, uncomment below:
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

